### PR TITLE
Add flag to skip subdirs

### PR DESCRIPTION
**Pull request by kyzn**
Hi! Thanks for maintaining AnyEvent::Filesys::Notify! It was my assignment for CPAN Pull Request Challenge - October 2017.

I was going through your TODO list, and found out you wanted to add a flag to skip recursion. I implemented one, and added some tests to make sure it's running fine. I hope you find it useful! Let me know if you want me to update anything.

This PR will probably let us close RT ticket at https://rt.cpan.org/Public/Bug/Display.html?id=104714.

Thanks!

\#cpan-prc \#hacktoberfest

### CODE REVIEW

**Comment by mvgrimes** [comment]
Thanks @kyzn. This looks good. I particularly appreciate the tests. 

We need to investigate the Travis failures before merging. It seems to be failing on older versions of perl (<5.18).

**Comment by kyzn** [comment]
Thanks for your kind comment @mvgrimes! You made a good point, I must have missed Travis failures. I'll take a look this weekend.

**Comment by kyzn** [comment]
- 5.12, 5.14, 5.16, 5.18 fails only the test I added. Looking into it now.
- 5.21 fails because of a perlbrew issue, and everything falls apart after that. From logs:
```$ perlbrew use 5.21

ERROR: The installation "5.21" is unknown.```

**Comment by kyzn** [comment]
Apparently I was missing a dot: I replaced `qr//` with `qr/./` and it seems to work fine on 5.16.3 now.
I'm guessing "5.21" will still fail because it's not available on perlbrew.

**Pull request merged**
